name: my_territory_app
description: A Flutter wrapper app for the My Territory web prototype.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/index.html
    - assets/style.css
    - assets/app.js
